language: java
dist: xenial
sudo: true
before_script:
#  - cp config/database.yml.travis config/database.yml
  - psql -c "create database stock;" -U postgres
  - psql -c "create database stock_test;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres


before_install:
  - chmod +x mvnw


services:
  - postgresql
jdk:
  - openjdk8
script: mvn clean install

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10