language: java
dist: xenial
sudo: true
before_script:
- psql -c "create database stock;" -U postgres
- psql -c "create database stock_test;" -U postgres
before_install:
- chmod +x mvnw
services:
- postgresql
jdk:
- openjdk8
script: mvn clean install
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  api_key:
    secure: FJAkTxUOq7Dr+wbuFLDYQIuLXpOYJegw0OjRDzzSSiKajuxKaxBLHLz7LxYJ4P4yUhYWURf9oAs+vGnXfA6GNWG4Qr18ywg8S8ahWlj6o+y3+bAYm3Wuoj/GkjHJhqAoAsRU1xhZIHJ3qV9LoUEdo0xURp/B52YgT4eO5quvfHaCD7K5xZ23YWyULcW4wp0MiJTDdJkLlLS8w+AtkWQWOyLhwD5uPNua67AxEwrQm9BdacNS2L8mWrVj7X0nSGGpxWDGAlooB8dhpts4pNH+OTnhqHWabzAfFKA/cXPuip/nJESbqxNpe3cGF1eDkXxVJn/dM9XdMzbF4tf4BsbWUDeb4aX6rui1idV1C24FHZxhq37VVhJrGcVHC0Ppf1aABwOCb0gBi2/grlrfOHqVC8+NetExMQl4nf8N5uyHysF4Du5hTK+8sifeyzBpGPS6HEoVQeAWlYNZsvD3v4yXb3bO/LF3XYg+n0tBHmpKttLdUQj68cQPQ+j+9A9drC6+IZeuTTMi833yQeH50VAzG0H7U1oUgpySIBvJW9oNWvtTTWomy9atlCSMH09bnY3unLikH6BV0+TCOIhVKA8diZrCbm+IPzi9PuPcAefV5aVZr07O9a9cdh2AZGVWRjfPNABEwhfEWQkrFBhh6nFjelhKPfhzyUhIU4cK0xhTQX4=
  app: stock-data-o
  on:
    branch: just
