version: '3'
services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stock
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    restart: always

  web-stock:
    image: bannes/stock-data:latest
    container_name: stock-app
    ports:
      - 8070:8070
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/stock
    restart: always
    links:
      - db
    depends_on:
      - db
